import { About } from '@/components/About';
import { Blog } from '@/components/Blog';
import { Contact } from '@/components/Contact';
import Main from '@/components/Main';
import Navbar from '@/components/Navbar';
import { Projects } from '@/components/Projects';
import { Skills } from '@/components/Skills';
import { TimeLine } from '@/components/TimeLine';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Matheus Filho | Desenvolvedor Front-End</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <div className="flex justify-center flex-col items-center">
        <div className="flex justify-center items-center">
          <h3 className="text-center tracking-widest font-extrabold text-2xl p-5 pb-3 m-4 text-[#5651e5] border-b-4 border-[#5651e5]">
            Minha Carreira
          </h3>
        </div>
        <TimeLine />
      </div>
      <Skills />
      <Projects />
      <Blog />
      <Contact />
    </div>
  );
}
